on:
  push:
    branches: main
  workflow_dispatch:

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            sysfonts
            ggplot2
            ggtext
            showtext
            knitr
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        run: |
          mkdir index
          cd index
          quarto use template --no-prompt ${{ github.repository }}
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          quarto publish gh-pages index.qmd
          cd ..
          rm -rf index
      - name: Render and Publish
        if: ${{ false }}
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          GITHUB_USERNAME: 
          GITHUB_EMAIL: 
          target: gh-pages
          path: template.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
